### ISSUE TITLE
RHCSA lab files 9 and 10 are out of order

### ISSUE THREAD

**Issue by dduclayan** [dmbrownlee/demo#23]
Hi dmbrownlee!

Just wanted to bring to your attn that it appears the lesson labs for chapters 9 and 10 are switched in the demo/rhcsa/labfiles directory. According to the video series for RHCSA, chapter 9 is now _Managing Processes_ and chapter 10 is _Managing Software_. But if we look at the labfiles directory in the current master branch we can see that it is the opposite.

Video Series - _Red Hat Certified System Administrator (RHCSA) with Virtual Machines, Second Edition_
[Link](https://learning.oreilly.com/videos/red-hat-certified/9780134723990/9780134723990-RHCA_02_10_LAB)

![chrome_7ZO66rlkyA](https://user-images.githubusercontent.com/19255490/93687092-a3daba00-fa80-11ea-81a6-a13082e4a797.png)
![chrome_fUDH2UCD1d](https://user-images.githubusercontent.com/19255490/93687093-a3daba00-fa80-11ea-8fbd-b99235fd7fc0.png)

![chrome_f7E4kQ8tGy](https://user-images.githubusercontent.com/19255490/93687221-8d812e00-fa81-11ea-8b9c-9f5430234959.png)
![chrome_HLb7KhvjPi](https://user-images.githubusercontent.com/19255490/93687220-8d812e00-fa81-11ea-8af3-b96c3a59e1b0.png)

**Comment by dmbrownlee** [comment]
First, the video series lessons don't exactly map to the book chapters and the lab file directories are organized to match the text book.  Second, chapters 9 and 10 swapped places between the RHCSA 7 and RHCSA 8 study guides.  I have a mapping of all the chapter changes between the books on an internal resource and I'll send you that link out of band.  The lab directories are should be aligned with the current study guide (available at https://www.oreilly.com/library/view/red-hat-rhcsa/9780135938058/ or https://www.amazon.com/Red-RHCSA-Cert-Guide-Certification/dp/0135938139).

I do see now our internal assignment docs have issues with the video links since the video lessons don't map directly to the same numbered chapters so I'll have to fix that.  However, I believe the chapter directories here on GitHub map correctly to the study guide links.  At least chapters 9 and 10 are correct.

Thanks for the report.  I'll send you the doc with chapter changes between RHCSA 7 and RHCSA 8 and check the video links in the assignment docs asap.
